package com.example.navkaran.easyattendance.models;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;

// David Cui B00788648 Nov 2018

/**
 * data holder for an course item, an entity(table) in the room database.
 */
@Entity(tableName = "courses",
        indices={@Index(value="course_key", unique=true)})
public class CourseItem {
    //autogenerated primary key is integer, different from the courseID
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "course_key")
    private int courseKey;
    //such as CSCI5100
    @ColumnInfo(name = "course_id")
    private String courseID;
    //full name of course
    @ColumnInfo(name = "course_name")
    private String courseName;
    //number of students in course
    @ColumnInfo(name = "course_student_count")
    private int studentCount;

    @Ignore
    public CourseItem(int courseKey, String courseID, String courseName, int studentCount) {
        this.courseKey = courseKey;
        this.courseID = courseID;
        this.courseName = courseName;
        this.studentCount = studentCount;
    }

    //this is used by room database to insert entries into table
    public CourseItem(String courseID, String courseName, int studentCount) {
        this.courseID = courseID;
        this.courseName = courseName;
        this.studentCount = studentCount;
    }

    public int getCourseKey() {
        return courseKey;
    }

    public void setCourseKey(int courseKey) {
        this.courseKey = courseKey;
    }

    public String getCourseID() {
        return courseID;
    }

    public String getCourseName() {
        return courseName;
    }

    public int getStudentCount() {
        return studentCount;
    }
}
