package com.example.navkaran.easyattendance.models;

import android.app.Application;
import android.arch.lifecycle.LiveData;
import android.os.AsyncTask;

import com.example.navkaran.easyattendance.models.AppDatabase;
import com.example.navkaran.easyattendance.models.Lecture;
import com.example.navkaran.easyattendance.models.LectureDAO;

import java.util.List;

// David Cui Nov 2018

/**
 * Repository provides an interface to deal with the database
 * Also uses AsyncTasks to make sure queries are done on worker threads
 */
public class LectureRepository {

    private LectureDAO lectureDAO;

    // access the db singleton and gets the DAO
    public LectureRepository(Application application) {
        AppDatabase db = AppDatabase.getInstance(application);
        lectureDAO = db.lectureDAO();
    }

    // uses course key to get all lectures for that course key in LiveData
    public LiveData<List<Lecture>> getLiveLecturesByCourseKey(int courseKey) {
        return lectureDAO.getLiveLecturesByCourseKey(courseKey);
    }

    public List<Lecture> getLecturesByCourseKey(int courseKey) throws Exception {
        return new GetLecturesAsyncTask(lectureDAO).execute(courseKey).get();
    }

    // insert a lecture, the primary key is autogenerated and returned
    public long insert (Lecture lecture) throws Exception {
        return new InsertAsyncTask(lectureDAO).execute(lecture).get();
    }

    // delete a lecture by the lectureId (primary key)
    public boolean deleteByLectureId (long lectureId) {
        try {
            new DeleteAsyncTask(lectureDAO).execute(lectureId);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    // async tasks
    private static class GetLecturesAsyncTask extends AsyncTask<Integer, Void, List<Lecture>> {

        private LectureDAO asyncTaskDAO;

        GetLecturesAsyncTask(LectureDAO dao) {
            asyncTaskDAO = dao;
        }

        @Override
        protected List<Lecture> doInBackground(final Integer... courseKey) {
            return asyncTaskDAO.getLecturesByCourseKey(courseKey[0]);
        }
    }

    private static class InsertAsyncTask extends AsyncTask<Lecture, Void, Long> {

        private LectureDAO asyncTaskDAO;

        InsertAsyncTask(LectureDAO dao) {
            asyncTaskDAO = dao;
        }

        @Override
        protected  Long doInBackground(final Lecture... lecture) {
            return asyncTaskDAO.insertLecture(lecture[0]);
        }
    }

    private static class DeleteAsyncTask extends AsyncTask<Long, Void, Void> {

        private LectureDAO asyncTaskDAO;

        DeleteAsyncTask(LectureDAO dao) {
            asyncTaskDAO = dao;
        }

        @Override
        protected Void doInBackground(final Long... lectureId) {
            asyncTaskDAO.deleteByLectureId(lectureId[0]);
            return null;
        }
    }
}
